import {
  Home,
  Utensils,
  Car,
  Heart,
  Gamepad2,
  Book,
  CreditCard,
  RefreshCw,
  ShoppingCart,
  Coffee,
  Banknote,
  PlusCircle,
  Plane,
  Gift,
  Dumbbell,
  Smartphone,
  Receipt,
  GraduationCap,
  Shirt,
  Wrench,
  TrendingUp,
  PiggyBank,
  Package,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  home: Home,
  utensils: Utensils,
  car: Car,
  heart: Heart,
  gamepad: Gamepad2,
  'gamepad-2': Gamepad2,
  book: Book,
  'credit-card': CreditCard,
  'refresh-cw': RefreshCw,
  'shopping-cart': ShoppingCart,
  coffee: Coffee,
  banknote: Banknote,
  'plus-circle': PlusCircle,
  plane: Plane,
  gift: Gift,
  dumbbell: Dumbbell,
  smartphone: Smartphone,
  receipt: Receipt,
  'graduation-cap': GraduationCap,
  shirt: Shirt,
  wrench: Wrench,
  'trending-up': TrendingUp,
  'piggy-bank': PiggyBank,
  package: Package,
}

export const PREDEFINED_ICONS = [
  'home',
  'shopping-cart',
  'car',
  'heart',
  'graduation-cap',
  'gamepad-2',
  'shirt',
  'wrench',
  'smartphone',
  'trending-up',
  'piggy-bank',
  'package',
  'credit-card',
  'book',
  'coffee',
  'banknote',
]

export const PREDEFINED_COLORS = [
  '#10b981',
  '#3b82f6',
  '#f59e0b',
  '#ef4444',
  '#8b5cf6',
  '#ec4899',
  '#14b8a6',
  '#6b7280',
  '#6366f1',
  '#22c55e',
  '#f97316',
  '#9ca3af',
]

export function getCategoryIcon(name: string): LucideIcon {
  return iconMap[name] || PlusCircle
}
